@echo off
vsa -h -0 VS0.vsh
vsa -h -0 VS1.vsh
vsa -h -0 VS2.vsh
vsa -h -0 VS3.vsh
vsa -h -0 VS4.vsh
vsa -h -0 VS5.vsh
vsa -h -0 VS6.vsh
vsa -h -0 VS7.vsh
psa -h -0 YCbCr.psh
vsa -h -0 debug.vsh
psa -h -0 debugPS.psh
psa -h -0 blend_dstzero_srczero.psh
psa -h -0 blend_dstzero_srcone.psh
psa -h -0 blend_dstzero_srcsrcalpha.psh
psa -h -0 blend_dstzero_srcinvsrcalpha.psh
psa -h -0 blend_dstzero_srcdestalpha.psh
psa -h -0 blend_dstzero_srcinvdestalpha.psh
psa -h -0 blend_dstone_srczero.psh
psa -h -0 blend_dstone_srcone.psh
psa -h -0 blend_dstone_srcsrcalpha.psh
psa -h -0 blend_dstone_srcdestalpha.psh
psa -h -0 blend_dstsrcalpha_srczero.psh
psa -h -0 blend_dstsrcalpha_srcone.psh
psa -h -0 blend_dstsrcalpha_srcinvsrcalpha.psh
psa -h -0 blend_dstinvsrcalpha_srczero.psh
psa -h -0 blend_dstinvsrcalpha_srcsrcalpha.psh
psa -h -0 blend_dstdestalpha_srczero.psh
psa -h -0 blend_dstdestalpha_srcone.psh
psa -h -0 blend_dstdestalpha_srcinvdestalpha.psh
psa -h -0 blend_dstinvdestalpha_srczero.psh
psa -h -0 blend_dstinvdestalpha_srcdestalpha.psh